# Generated by Django 6.0.6 on 2026-06-28 14:12

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='transaction.transactiontype', verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='transaction.category', verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='transaction_type', chained_model_field='transaction_type', on_delete=django.db.models.deletion.PROTECT, to='transaction.category', verbose_name='Категория транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, to='transaction.subcategory', verbose_name='Подкатегория транзакции'),
        ),
    ]
