# Generated by Django 6.0.6 on 2026-06-29 02:43

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_category_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
